const assert = require('node:assert/strict');
const {count,summarize,createCycle}=require('../PayTimeWebClient/Pages_JS/Dashboard/MinopInsights.js');
assert.equal(summarize({1:75,6:25,3:4,4:2}).rate,75);
assert.equal(summarize({1:0,6:0}).rate,null);
assert.equal(summarize({1:0,6:10}).rate,0);
assert.equal(summarize({1:10}).rate,null);
for(const invalid of [null,undefined,'',false,-1,NaN,Infinity,'12 people','1.5',Number.MAX_SAFE_INTEGER+1]) assert.equal(count(invalid),null);
assert.equal(count('0'),0);
assert.equal(summarize({1:1,6:2}).rate,33.3);
const cycle=createCycle(), old={}, next={}, absent={};
cycle.start('a/1',1,old); cycle.start('b/2',1,next); cycle.start('b/2',6,absent);
assert.equal(cycle.finish('a/1',1,old,999),false);
assert.equal(cycle.finish('b/2',1,next,10),true);
assert.equal(summarize(cycle.snapshot().values).rate,null);
assert.equal(cycle.snapshot().loading,true);
cycle.finish('b/2',6,absent,0);
assert.equal(summarize(cycle.snapshot().values).rate,100);
assert.equal(cycle.snapshot().loading,false);
const retry={}; cycle.start('b/2',1,retry);
assert.deepEqual(cycle.snapshot().values,{});
assert.equal(cycle.finish('b/2',1,next,500),false);
cycle.finish('b/2',1,retry,null);
assert.equal(summarize(cycle.snapshot().values).rate,null);
console.log('PASS: ratios, zero/missing/invalid values, scope changes, stale responses, refresh reset and failed requests');
