//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayTimeWebClient.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayTimeWebClient.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        public static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active monitoring with live Dash boards.
        /// </summary>
        public static string ActiveMonitoringWithLiveDashBoards {
            get {
                return ResourceManager.GetString("ActiveMonitoringWithLiveDashBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Company.
        /// </summary>
        public static string AddCompany {
            get {
                return ResourceManager.GetString("AddCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template.
        /// </summary>
        public static string Addreporttemplate {
            get {
                return ResourceManager.GetString("Addreporttemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Login.
        /// </summary>
        public static string adminlogin {
            get {
                return ResourceManager.GetString("adminlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Payroll.
        /// </summary>
        public static string AdvancedPayroll {
            get {
                return ResourceManager.GetString("AdvancedPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazing.
        /// </summary>
        public static string Amazing {
            get {
                return ResourceManager.GetString("Amazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance policy configuration.
        /// </summary>
        public static string Attendancepolicyconfiguration {
            get {
                return ResourceManager.GetString("Attendancepolicyconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Summary.
        /// </summary>
        public static string AttendanceSummary {
            get {
                return ResourceManager.GetString("AttendanceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Work.
        /// </summary>
        public static string AtWork {
            get {
                return ResourceManager.GetString("AtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open/close.
        /// </summary>
        public static string ClickToOpenClose {
            get {
                return ResourceManager.GetString("ClickToOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        public static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Company Email ID.
        /// </summary>
        public static string CompanyEmailValidation {
            get {
                return ResourceManager.GetString("CompanyEmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company ID.
        /// </summary>
        public static string CompanyID {
            get {
                return ResourceManager.GetString("CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name must be greater than 3 character.
        /// </summary>
        public static string CompanyNameLengthValidation {
            get {
                return ResourceManager.GetString("CompanyNameLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Company name.
        /// </summary>
        public static string CompanyNameValidation {
            get {
                return ResourceManager.GetString("CompanyNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Settings.
        /// </summary>
        public static string CompanySettings {
            get {
                return ResourceManager.GetString("CompanySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Website.
        /// </summary>
        public static string CompanyWebsite {
            get {
                return ResourceManager.GetString("CompanyWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive shift processing.
        /// </summary>
        public static string ComprehensiveShiftProcessing {
            get {
                return ResourceManager.GetString("ComprehensiveShiftProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string CreateAnAccount {
            get {
                return ResourceManager.GetString("CreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Report.
        /// </summary>
        public static string CustomReport {
            get {
                return ResourceManager.GetString("CustomReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device configuration on Network.
        /// </summary>
        public static string DeviceConfigurationOnNetwork {
            get {
                return ResourceManager.GetString("DeviceConfigurationOnNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download App.
        /// </summary>
        public static string DownloadApp {
            get {
                return ResourceManager.GetString("DownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early OUT.
        /// </summary>
        public static string EarlyOUT {
            get {
                return ResourceManager.GetString("EarlyOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Email ID..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Login.
        /// </summary>
        public static string emplogin {
            get {
                return ResourceManager.GetString("emplogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee At Work.
        /// </summary>
        public static string EmployeeAtWork {
            get {
                return ResourceManager.GetString("EmployeeAtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee on Leave.
        /// </summary>
        public static string EmployeeonLeave {
            get {
                return ResourceManager.GetString("EmployeeonLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Download.
        /// </summary>
        public static string FreeDownload {
            get {
                return ResourceManager.GetString("FreeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Summary.
        /// </summary>
        public static string HoursSummary {
            get {
                return ResourceManager.GetString("HoursSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home | Mantra.
        /// </summary>
        public static string IndexPagetitle {
            get {
                return ResourceManager.GetString("IndexPagetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late IN.
        /// </summary>
        public static string LateIN {
            get {
                return ResourceManager.GetString("LateIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Management.
        /// </summary>
        public static string LeaveManagement {
            get {
                return ResourceManager.GetString("LeaveManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave management with ESS.
        /// </summary>
        public static string LeaveManagementWithESS {
            get {
                return ResourceManager.GetString("LeaveManagementWithESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Summary.
        /// </summary>
        public static string LeaveSummary {
            get {
                return ResourceManager.GetString("LeaveSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View MINOP&apos;s Live Demo?.
        /// </summary>
        public static string LiveDemo {
            get {
                return ResourceManager.GetString("LiveDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        public static string LoginToYourAccount {
            get {
                return ResourceManager.GetString("LoginToYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B203, Shapath Hexa,.
        /// </summary>
        public static string MantraAdd1 {
            get {
                return ResourceManager.GetString("MantraAdd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.G. Highway, Sola, Ahmedabad.
        /// </summary>
        public static string MantraAdd2 {
            get {
                return ResourceManager.GetString("MantraAdd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Fingerprint Identification System(AFIS) and software for fingerprint identification search matching / finger print recognition are the primary products of Mantra Technologies. We provide the accuracy criminal and civil fingerprint identification search and authentication systems in the industry. Company is not only powerful manufacturer of skin biometric time tracker products, but haivng their own supply chain across india with leading biometrics dealers, distributors and other biometrics supplier [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Mantradesc {
            get {
                return ResourceManager.GetString("Mantradesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 079 30009444.
        /// </summary>
        public static string MantraPhNo {
            get {
                return ResourceManager.GetString("MantraPhNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon-Fri 9am-6pm.
        /// </summary>
        public static string MantraTime {
            get {
                return ResourceManager.GetString("MantraTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantra Softech (India) Pvt Ltd is a leader in Biometric security and Business solutions..
        /// </summary>
        public static string Mantratitle {
            get {
                return ResourceManager.GetString("Mantratitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About​.
        /// </summary>
        public static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string mnuFeatures {
            get {
                return ResourceManager.GetString("mnuFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string mnuHome {
            get {
                return ResourceManager.GetString("mnuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login​.
        /// </summary>
        public static string mnuLogin {
            get {
                return ResourceManager.GetString("mnuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string mnuPricing {
            get {
                return ResourceManager.GetString("mnuPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string mnuService {
            get {
                return ResourceManager.GetString("mnuService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string mnuSupport {
            get {
                return ResourceManager.GetString("mnuSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Report StartDay.
        /// </summary>
        public static string MonthlyReportStartDay {
            get {
                return ResourceManager.GetString("MonthlyReportStartDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Branch.
        /// </summary>
        public static string MultipleBranch {
            get {
                return ResourceManager.GetString("MultipleBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to Display.
        /// </summary>
        public static string Nodatatodisplay {
            get {
                return ResourceManager.GetString("Nodatatodisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online support.
        /// </summary>
        public static string Onlinesupport {
            get {
                return ResourceManager.GetString("Onlinesupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization hierarchy.
        /// </summary>
        public static string Organizationhierarchy {
            get {
                return ResourceManager.GetString("Organizationhierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Offices.
        /// </summary>
        public static string OurOffices {
            get {
                return ResourceManager.GetString("OurOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Pricing.
        /// </summary>
        public static string OurPricing {
            get {
                return ResourceManager.GetString("OurPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Service.
        /// </summary>
        public static string OurService {
            get {
                return ResourceManager.GetString("OurService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length must be greater than 6 &amp; less than 15 characters..
        /// </summary>
        public static string PasswordlengthValidation {
            get {
                return ResourceManager.GetString("PasswordlengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        public static string PhotoGallery {
            get {
                return ResourceManager.GetString("PhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Email.
        /// </summary>
        public static string PleaseEnterYourEmail {
            get {
                return ResourceManager.GetString("PleaseEnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful. Activation email has been sent..
        /// </summary>
        public static string RegistrationSucessfull {
            get {
                return ResourceManager.GetString("RegistrationSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string rememberme {
            get {
                return ResourceManager.GetString("rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Branch.
        /// </summary>
        public static string SelectBranch {
            get {
                return ResourceManager.GetString("SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting ID.
        /// </summary>
        public static string SettingID {
            get {
                return ResourceManager.GetString("SettingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Branch.
        /// </summary>
        public static string SingleBranch {
            get {
                return ResourceManager.GetString("SingleBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-friendly platform for an empowered workforce!.
        /// </summary>
        public static string slider1Body {
            get {
                return ResourceManager.GetString("slider1Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME &amp; ATTENDANCE MANAGEMENT.
        /// </summary>
        public static string slider1Header {
            get {
                return ResourceManager.GetString("slider1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string slider1Registerbtn {
            get {
                return ResourceManager.GetString("slider1Registerbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Live Attendance Status and Reports.
        /// </summary>
        public static string slider2Body {
            get {
                return ResourceManager.GetString("slider2Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize with your Attendance Device.
        /// </summary>
        public static string slider2Header {
            get {
                return ResourceManager.GetString("slider2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportune easy to use shift planning function gives extensive flexibility to the shift planner..
        /// </summary>
        public static string slider3Body {
            get {
                return ResourceManager.GetString("slider3Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifting Scheduling.
        /// </summary>
        public static string slider3Header {
            get {
                return ResourceManager.GetString("slider3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS &amp; Email Alert Services..
        /// </summary>
        public static string SMSAndEmailAlertServices {
            get {
                return ResourceManager.GetString("SMSAndEmailAlertServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Mobile No.
        /// </summary>
        public static string SMSMobileNo {
            get {
                return ResourceManager.GetString("SMSMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr. no.
        /// </summary>
        public static string Srno {
            get {
                return ResourceManager.GetString("Srno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to our Newsletter.
        /// </summary>
        public static string SubscribeToOurNewsletter {
            get {
                return ResourceManager.GetString("SubscribeToOurNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party integration services.
        /// </summary>
        public static string ThirdPartyIntegrationServices {
            get {
                return ResourceManager.GetString("ThirdPartyIntegrationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time &amp; Attendance.
        /// </summary>
        public static string TimeAndAttendance {
            get {
                return ResourceManager.GetString("TimeAndAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Employees.
        /// </summary>
        public static string TotalEmployees {
            get {
                return ResourceManager.GetString("TotalEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined reporting system.
        /// </summary>
        public static string UserDefinedReportingSystem {
            get {
                return ResourceManager.GetString("UserDefinedReportingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View MINOP&apos;s Live Employee Demo?.
        /// </summary>
        public static string ViewMINOPsLiveEmployeeDemo {
            get {
                return ResourceManager.GetString("ViewMINOPsLiveEmployeeDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        public static string WebsiteURL {
            get {
                return ResourceManager.GetString("WebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To  MINOP CLOUD!.
        /// </summary>
        public static string welcometitle {
            get {
                return ResourceManager.GetString("welcometitle", resourceCulture);
            }
        }
    }
}
