using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace PayTimeWebClient.Models.ReportsModel
{
    public class MonthlyMuster
    {
        #region Properties
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public DateTime Attn_Dt { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public string D4 { get; set; }
        public string D5 { get; set; }
        public string D6 { get; set; }
        public string D7 { get; set; }
        public string D8 { get; set; }
        public string D9 { get; set; }
        public string D10 { get; set; }
        public string D11 { get; set; }
        public string D12 { get; set; }
        public string D13 { get; set; }
        public string D14 { get; set; }
        public string D15 { get; set; }
        public string D16 { get; set; }
        public string D17 { get; set; }
        public string D18 { get; set; }
        public string D19 { get; set; }
        public string D20 { get; set; }
        public string D21 { get; set; }
        public string D22 { get; set; }
        public string D23 { get; set; }
        public string D24 { get; set; }
        public string D25 { get; set; }
        public string D26 { get; set; }
        public string D27 { get; set; }
        public string D28 { get; set; }
        public string D29 { get; set; }
        public string D30 { get; set; }
        public string D31 { get; set; }
        public string D01_IN { get; set; }
        public string D02_IN { get; set; }
        public string D03_IN { get; set; }
        public string D04_IN { get; set; }
        public string D05_IN { get; set; }
        public string D06_IN { get; set; }
        public string D07_IN { get; set; }
        public string D08_IN { get; set; }
        public string D09_IN { get; set; }
        public string D10_IN { get; set; }
        public string D11_IN { get; set; }
        public string D12_IN { get; set; }
        public string D13_IN { get; set; }
        public string D14_IN { get; set; }
        public string D15_IN { get; set; }
        public string D16_IN { get; set; }
        public string D17_IN { get; set; }
        public string D18_IN { get; set; }
        public string D19_IN { get; set; }
        public string D20_IN { get; set; }
        public string D21_IN { get; set; }
        public string D22_IN { get; set; }
        public string D23_IN { get; set; }
        public string D24_IN { get; set; }
        public string D25_IN { get; set; }
        public string D26_IN { get; set; }
        public string D27_IN { get; set; }
        public string D28_IN { get; set; }
        public string D29_IN { get; set; }
        public string D30_IN { get; set; }
        public string D31_IN { get; set; }
        public string D01_OUT { get; set; }
        public string D02_OUT { get; set; }
        public string D03_OUT { get; set; }
        public string D04_OUT { get; set; }
        public string D05_OUT { get; set; }
        public string D06_OUT { get; set; }
        public string D07_OUT { get; set; }
        public string D08_OUT { get; set; }
        public string D09_OUT { get; set; }
        public string D10_OUT { get; set; }
        public string D11_OUT { get; set; }
        public string D12_OUT { get; set; }
        public string D13_OUT { get; set; }
        public string D14_OUT { get; set; }
        public string D15_OUT { get; set; }
        public string D16_OUT { get; set; }
        public string D17_OUT { get; set; }
        public string D18_OUT { get; set; }
        public string D19_OUT { get; set; }
        public string D20_OUT { get; set; }
        public string D21_OUT { get; set; }
        public string D22_OUT { get; set; }
        public string D23_OUT { get; set; }
        public string D24_OUT { get; set; }
        public string D25_OUT { get; set; }
        public string D26_OUT { get; set; }
        public string D27_OUT { get; set; }
        public string D28_OUT { get; set; }
        public string D29_OUT { get; set; }
        public string D30_OUT { get; set; }
        public string D31_OUT { get; set; }
        public string D01_O { get; set; }
        public string D02_O { get; set; }
        public string D03_O { get; set; }
        public string D04_O { get; set; }
        public string D05_O { get; set; }
        public string D06_O { get; set; }
        public string D07_O { get; set; }
        public string D08_O { get; set; }
        public string D09_O { get; set; }
        public string D10_O { get; set; }
        public string D11_O { get; set; }
        public string D12_O { get; set; }
        public string D13_O { get; set; }
        public string D14_O { get; set; }
        public string D15_O { get; set; }
        public string D16_O { get; set; }
        public string D17_O { get; set; }
        public string D18_O { get; set; }
        public string D19_O { get; set; }
        public string D20_O { get; set; }
        public string D21_O { get; set; }
        public string D22_O { get; set; }
        public string D23_O { get; set; }
        public string D24_O { get; set; }
        public string D25_O { get; set; }
        public string D26_O { get; set; }
        public string D27_O { get; set; }
        public string D28_O { get; set; }
        public string D29_O { get; set; }
        public string D30_O { get; set; }
        public string D31_O { get; set; }
        public string D01_L { get; set; }
        public string D02_L { get; set; }
        public string D03_L { get; set; }
        public string D04_L { get; set; }
        public string D05_L { get; set; }
        public string D06_L { get; set; }
        public string D07_L { get; set; }
        public string D08_L { get; set; }
        public string D09_L { get; set; }
        public string D10_L { get; set; }
        public string D11_L { get; set; }
        public string D12_L { get; set; }
        public string D13_L { get; set; }
        public string D14_L { get; set; }
        public string D15_L { get; set; }
        public string D16_L { get; set; }
        public string D17_L { get; set; }
        public string D18_L { get; set; }
        public string D19_L { get; set; }
        public string D20_L { get; set; }
        public string D21_L { get; set; }
        public string D22_L { get; set; }
        public string D23_L { get; set; }
        public string D24_L { get; set; }
        public string D25_L { get; set; }
        public string D26_L { get; set; }
        public string D27_L { get; set; }
        public string D28_L { get; set; }
        public string D29_L { get; set; }
        public string D30_L { get; set; }
        public string D31_L { get; set; }
        public string D01_T { get; set; }
        public string D02_T { get; set; }
        public string D03_T { get; set; }
        public string D04_T { get; set; }
        public string D05_T { get; set; }
        public string D06_T { get; set; }
        public string D07_T { get; set; }
        public string D08_T { get; set; }
        public string D09_T { get; set; }
        public string D10_T { get; set; }
        public string D11_T { get; set; }
        public string D12_T { get; set; }
        public string D13_T { get; set; }
        public string D14_T { get; set; }
        public string D15_T { get; set; }
        public string D16_T { get; set; }
        public string D17_T { get; set; }
        public string D18_T { get; set; }
        public string D19_T { get; set; }
        public string D20_T { get; set; }
        public string D21_T { get; set; }
        public string D22_T { get; set; }
        public string D23_T { get; set; }
        public string D24_T { get; set; }
        public string D25_T { get; set; }
        public string D26_T { get; set; }
        public string D27_T { get; set; }
        public string D28_T { get; set; }
        public string D29_T { get; set; }
        public string D30_T { get; set; }
        public string D31_T { get; set; }
        public string D01_E { get; set; }
        public string D02_E { get; set; }
        public string D03_E { get; set; }
        public string D04_E { get; set; }
        public string D05_E { get; set; }
        public string D06_E { get; set; }
        public string D07_E { get; set; }
        public string D08_E { get; set; }
        public string D09_E { get; set; }
        public string D10_E { get; set; }
        public string D11_E { get; set; }
        public string D12_E { get; set; }
        public string D13_E { get; set; }
        public string D14_E { get; set; }
        public string D15_E { get; set; }
        public string D16_E { get; set; }
        public string D17_E { get; set; }
        public string D18_E { get; set; }
        public string D19_E { get; set; }
        public string D20_E { get; set; }
        public string D21_E { get; set; }
        public string D22_E { get; set; }
        public string D23_E { get; set; }
        public string D24_E { get; set; }
        public string D25_E { get; set; }
        public string D26_E { get; set; }
        public string D27_E { get; set; }
        public string D28_E { get; set; }
        public string D29_E { get; set; }
        public string D30_E { get; set; }
        public string D31_E { get; set; }
        public string D01_S { get; set; }
        public string D02_S { get; set; }
        public string D03_S { get; set; }
        public string D04_S { get; set; }
        public string D05_S { get; set; }
        public string D06_S { get; set; }
        public string D07_S { get; set; }
        public string D08_S { get; set; }
        public string D09_S { get; set; }
        public string D10_S { get; set; }
        public string D11_S { get; set; }
        public string D12_S { get; set; }
        public string D13_S { get; set; }
        public string D14_S { get; set; }
        public string D15_S { get; set; }
        public string D16_S { get; set; }
        public string D17_S { get; set; }
        public string D18_S { get; set; }
        public string D19_S { get; set; }
        public string D20_S { get; set; }
        public string D21_S { get; set; }
        public string D22_S { get; set; }
        public string D23_S { get; set; }
        public string D24_S { get; set; }
        public string D25_S { get; set; }
        public string D26_S { get; set; }
        public string D27_S { get; set; }
        public string D28_S { get; set; }
        public string D29_S { get; set; }
        public string D30_S { get; set; }
        public string D31_S { get; set; }
        public double Tot_Attn { get; set; }
        public double Tot_Abs { get; set; }
        public int Tot_WeekOFF { get; set; }
        public int Tot_Holiday { get; set; }
        public string TotHour { get; set; }
        public int Tot_HD { get; set; }
        public string Tot_Early { get; set; }
        public string Tot_Late { get; set; }
        public string Tot_OT { get; set; }
        public int Tot_OD { get; set; }
        public decimal Tot_Leave { get; set; }
        public int Count_Late { get; set; }
        public int Count_Early { get; set; }
        public int Count_OT { get; set; }
        public string D01_W { get; set; }
        public string D02_W { get; set; }
        public string D03_W { get; set; }
        public string D04_W { get; set; }
        public string D05_W { get; set; }
        public string D06_W { get; set; }
        public string D07_W { get; set; }
        public string D08_W { get; set; }
        public string D09_W { get; set; }
        public string D10_W { get; set; }
        public string D11_W { get; set; }
        public string D12_W { get; set; }
        public string D13_W { get; set; }
        public string D14_W { get; set; }
        public string D15_W { get; set; }
        public string D16_W { get; set; }
        public string D17_W { get; set; }
        public string D18_W { get; set; }
        public string D19_W { get; set; }
        public string D20_W { get; set; }
        public string D21_W { get; set; }
        public string D22_W { get; set; }
        public string D23_W { get; set; }
        public string D24_W { get; set; }
        public string D25_W { get; set; }
        public string D26_W { get; set; }
        public string D27_W { get; set; }
        public string D28_W { get; set; }
        public string D29_W { get; set; }
        public string D30_W { get; set; }
        public string D31_W { get; set; }
        public string D01_H { get; set; }
        public string D02_H { get; set; }
        public string D03_H { get; set; }
        public string D04_H { get; set; }
        public string D05_H { get; set; }
        public string D06_H { get; set; }
        public string D07_H { get; set; }
        public string D08_H { get; set; }
        public string D09_H { get; set; }
        public string D10_H { get; set; }
        public string D11_H { get; set; }
        public string D12_H { get; set; }
        public string D13_H { get; set; }
        public string D14_H { get; set; }
        public string D15_H { get; set; }
        public string D16_H { get; set; }
        public string D17_H { get; set; }
        public string D18_H { get; set; }
        public string D19_H { get; set; }
        public string D20_H { get; set; }
        public string D21_H { get; set; }
        public string D22_H { get; set; }
        public string D23_H { get; set; }
        public string D24_H { get; set; }
        public string D25_H { get; set; }
        public string D26_H { get; set; }
        public string D27_H { get; set; }
        public string D28_H { get; set; }
        public string D29_H { get; set; }
        public string D30_H { get; set; }
        public string D31_H { get; set; }
        public string Tot_OTWO { get; set; }
        public string Tot_OTHO { get; set; }
        public int TotWO_Original { get; set; }
        public int TotHO_Original { get; set; }
        public decimal Tot_UnPaidLeave { get; set; }
        public string ShiftName { get; set; }
        public string ShiftStartTime { get; set; }
        public string ShiftEndTime { get; set; }
        public decimal TotalUnPaidLeave { get; set; }
        public string BranchName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public string CompanyName { get; set; }
        public decimal P { get; set; }
        public decimal A { get; set; }
        public decimal WO { get; set; }
        public decimal H { get; set; }
        public decimal PL { get; set; }
        public decimal PH { get; set; }
        public decimal OT { get; set; }
        public int MonthRepostartday { get; set; }
        public int LastdayMonth { get; set; }
        public string EmpCode { get; set; }
        public string PFromDate { get; set; }
        public string PTodate { get; set; }
        public string CompanyAddress { get; set; }
        public string TotalMin { get; set; }
        public string OTHr { get; set; }
        public string P_day { get; set; }

        public string Leavetype { get; set; }
        public string Leavecnt { get; set; }
        public string Levlst { get; set; }
		
		public string PunchID { get; set; }
        public string L1 { get; set; }
        public string L2 { get; set; }
        public string L3 { get; set; }
        public string L4 { get; set; }
        public string L5 { get; set; }
        public string L6 { get; set; }
        public string L7 { get; set; }
        public string L8 { get; set; }
        public string L9 { get; set; }
        public string L10 { get; set; }
        public string L11 { get; set; }
        public string L12 { get; set; }
        public string L13 { get; set; }
        public string L14 { get; set; }
        public string L15 { get; set; }
        public string L16 { get; set; }
        public string L17 { get; set; }
        public string L18 { get; set; }
        public string L19 { get; set; }
        public string L20 { get; set; }
        public string L21 { get; set; }
        public string L22 { get; set; }
        public string L23 { get; set; }
        public string L24 { get; set; }
        public string L25 { get; set; }
        public string L26 { get; set; }
        public string L27 { get; set; }
        public string L28 { get; set; }
        public string L29 { get; set; }
        public string L30 { get; set; }
        public string L31 { get; set; }
        public string L32 { get; set; }
        public string L33 { get; set; }
        public string L34 { get; set; }
        public string L35 { get; set; }
        public string L36 { get; set; }
        public string L37 { get; set; }
        public string L38 { get; set; }
        public string L39 { get; set; }
        public string L40 { get; set; }
        public string L41 { get; set; }
        public string L42 { get; set; }
        public string L43 { get; set; }
        public string L44 { get; set; }
        public string L45 { get; set; }
        public string L46 { get; set; }
        public string L47 { get; set; }
        public string L48 { get; set; }
        public string L49 { get; set; }
        public string L50 { get; set; }
        public string L51 { get; set; }
        public string L52 { get; set; }
        public string L53 { get; set; }
        public string L54 { get; set; }
        public string L55 { get; set; }
        public string L56 { get; set; }
        public string L57 { get; set; }
        public string L58 { get; set; }
        public string L59 { get; set; }
        public string L60 { get; set; }


        #endregion
    }
    public class MonthlyMusterCustom
    {
        #region Properties
        public string EmpName { get; set; }
        public double Total_Present { get; set; }
        public double Total_Absent { get; set; }
        public int Total_WeekOFF { get; set; }
        public int Total_Holiday { get; set; }
        public string TotHour { get; set; }
        public decimal Total_PaidLeave { get; set; }
        public string BranchName { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
        public string CompanyName { get; set; }
        public string EmpCode { get; set; }
        public string CompanyAddress { get; set; }
        #endregion
    }
    public class Workingduration
    {
        public string CompanyName { get; set; }
        public DateTime Attn_dt { get; set; }
        public string Empid { get; set; }
        public string EmpName { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Branch { get; set; }
        public string Shift { get; set; }
        public string Status { get; set; }
        public string col_1 { get; set; }
        public string col_2 { get; set; }
        public string col_3 { get; set; }
        public string col_4 { get; set; }
        public string col_5 { get; set; }
        public string col_6 { get; set; }
        public string col_7 { get; set; }
        public string col_8 { get; set; }
        public string col_9 { get; set; }
        public string col_10 { get; set; }
        public string col_11 { get; set; }
        public string col_12 { get; set; }
        public string col_13 { get; set; }
        public string col_14 { get; set; }
        public string col_15 { get; set; }
        public string col_16 { get; set; }
        public string col_17 { get; set; }
        public string col_18 { get; set; }
        public string col_19 { get; set; }
        public string col_20 { get; set; }
        public string col_21 { get; set; }
        public string col_22 { get; set; }
        public string col_23 { get; set; }
        public string col_24 { get; set; }
        public string col_25 { get; set; }
        public string col_26 { get; set; }
        public string col_27 { get; set; }
        public string col_28 { get; set; }
        public string col_29 { get; set; }
        public string col_30 { get; set; }
        public string col_31 { get; set; }
        public string Total { get; set; }
        public string Grpclm { get; set; }
        public int MonthRepostartday { get; set; }
        public int LastdayMonth { get; set; }
        public string EmpCode { get; set; }
        public string TotalFinal { get; set; }
        public string PFromDate { get; set; }
        public string PTodate { get; set; }
        public string CompanyAddress { get; set; }
        public decimal P { get; set; }
        public decimal A { get; set; }
        public decimal WO { get; set; }
        public decimal HO { get; set; }
        public decimal HD { get; set; }
        public decimal E { get; set; }
        
        
    }
    public class reqMonthlyReport
    {
        public string FromDate { get; set; }
        public string Todate { get; set; }
        public string EmpID { get; set; }
        public string ReportName { get; set; }
        public int CompanyId { get; set; }
    }
    public class PrintSummaryreport
    {
        public string CompanyAddress { get; set; }
        public string CompanyName { get; set; }
        public string BranchName { get; set; }
        public string DepartmentName { get; set; }
        public DateTime Attn_dt { get; set; }
        public int TotalEmployeeCount { get; set; }
        public int Present { get; set; }
        public int AttAbsent { get; set; }
        public int AttLeave { get; set; }
        public int WeeklyOff { get; set; }
        public int Holiday { get; set; }
        public int AttError { get; set; }
        public decimal EarlyInHrs { get; set; }
        public int EarlyInCount { get; set; }
        public string PFromDate { get; set; }
        public string PTodate { get; set; }
    }

    public class MonthlyKmReport
    {
        #region Properties
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public DateTime Attn_Dt { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
        public string D4 { get; set; }
        public string D5 { get; set; }
        public string D6 { get; set; }
        public string D7 { get; set; }
        public string D8 { get; set; }
        public string D9 { get; set; }
        public string D10 { get; set; }
        public string D11 { get; set; }
        public string D12 { get; set; }
        public string D13 { get; set; }
        public string D14 { get; set; }
        public string D15 { get; set; }
        public string D16 { get; set; }
        public string D17 { get; set; }
        public string D18 { get; set; }
        public string D19 { get; set; }
        public string D20 { get; set; }
        public string D21 { get; set; }
        public string D22 { get; set; }
        public string D23 { get; set; }
        public string D24 { get; set; }
        public string D25 { get; set; }
        public string D26 { get; set; }
        public string D27 { get; set; }
        public string D28 { get; set; }
        public string D29 { get; set; }
        public string D30 { get; set; }
        public string D31 { get; set; }
        public int MonthRepostartday { get; set; }
        public int LastdayMonth { get; set; }
        public string EmpCode { get; set; }
        public string PFromDate { get; set; }
        public string PTodate { get; set; }
        public decimal P { get; set; }
        public decimal A { get; set; }
        public decimal TotalKM { get; set; }

        public string TotHour { get; set; }
        public string TotalPunches { get; set; }

        public string BranchName { get; set;}

        public string DepartmentName { get; set; }

        #endregion
    }
}